apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   #host.docker.internal
   #localhost
   url: http://host.docker.internal:9090
   jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
