{
 "title": "Iron metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Среднее количество запросов на запись диск",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "windows_logical_disk_avg_write_requests_queued",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (mode) (irate(windows_cpu_time_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее количество запросов на чтение диска",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "windows_logical_disk_avg_read_requests_queued",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM: used bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "windows_os_visible_memory_bytes - windows_os_virtual_memory_free_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_os_visible_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}