apiVersion: 1


# # on what's available in the database
datasources:
 - name: Prometheus
   type: prometheus
   url: http://host.docker.internal:9090
   jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      httpHeaderName1: "Authorization"
      prometheusVersion: 2.47.0